### ISSUE TITLE
Run model on a CPU?

### ISSUE THREAD

**Issue by nicolagheza** [daniel-kukiela/nmt-chatbot#58]
Hello, would it be possible to run the trained model on a CPU?
I download the 'demo model' from dropbox but when I run the inference.py from my laptop I get:
`ImportError:` libcublas.so.8.0: cannot open shared object file: No such file or directory`

Does the model need a GPU also in production?

**Comment by daniel-kukiela** [comment]
Yes, you can run it on CPU.
```
pip uninstall tensorflow-gpu
pip install tensorflow
```
Change `pip` to whatever you are using, probably `pip3` or `pip3.6`

**Comment by nicolagheza** [comment]
Thanks, it worked. 
But I had to use tensorflow==1.4 to make it run properly. 
With 1.7 I had some errors.

**Comment by daniel-kukiela** [comment]
Can you tell me more about those errors? I think i might know what your issues are.
Also can you tell me what CPU are you using (model of CPU)?

**Comment by daniel-kukiela** [comment]
So the problem was not what i was thinking it is.

As for responses - it's pretty normal at the training begionning. How many training pairs and how log model is training now?

**Comment by nicolagheza** [comment]
What do you mean by that? Log model?
I have been using the pre-trained model to test it out. I did not train it
myseld. I am trying to get it to train on Google ML engine because I don't
have a GPU. Can I just train it starting from your pre-trained model and
the available data?

**Comment by daniel-kukiela** [comment]
Oh, so it's a very simple model trained quickly, as i didn't have resources for a longer training.
You can train more, you need to prepare your training set ang go through all steps to prepare and train your model. The reason for that is preparation steps makes files (training data and vocab files) for training set you are using.
